### ISSUE TITLE
Configuração da API - Retrofit

### ISSUE THREAD

**Issue by lucashos** [filipecancio/popcorn#5]
[RetrofitClient](https://github.com/filipecancio/filmin/blob/main/app/src/main/java/dev/cancio/filmin/repository/RetrofitClient.kt)

A classe RetrofitClient deve ser exclusiva para a configuração do client do retrofit.
Essa configuração fica numa estrutura denominada Core, onde se centralizam as partes configuráveis e comuns da aplicação.

A interface das APIs fica num contexto separado, onde se centralizam os provedores de dados, seja API, Banco de Dados, etc.

**Comment by filipecancio** [comment]
Tsc, o service iria ser o que é o API. Eu vou remover esses de service
