### ISSUE TITLE
Criar README

### ISSUE THREAD

**Issue by lucashos** [filipecancio/popcorn#7]
Criar um README, preferencialmente em ingles, contendo:

- Introdução sobre o projeto
- Stack de tecnologias utilizadas
- Referencias
- Instruções sobre o projeto
- Orientação sobre a estrutura de branches

**Comment by filipecancio** [comment]
- [ ] Introdução sobre o projeto
- [ ] Stack de tecnologias utilizadas
- [ ] Referencias
- [ ] Instruções sobre o projeto
- [ ] Orientação sobre a estrutura de branches
