### ISSUE TITLE
Configurar Github Actions

### ISSUE THREAD

**Issue by lucashos** [filipecancio/popcorn#8]
Configurar o Actions e adicionar hook para o README mostrando a estabilidade da aplicação

**Comment by filipecancio** [comment]
Achei um artigo legal no [RayWenderlich](https://www.raywenderlich.com/19407406-continuous-delivery-for-android-using-github-actions), vou tentar me basear no mobelo, acho que por agr só fazer o build ta legal mas posteriormente seria legal umas action de testes

**Comment by filipecancio** [comment]
Faltou o badge
